// Code generated by gjrpc. DO NOT EDIT.

package rpc

import (
	"encoding/json"
	jsonrpc "github.com/rwlist/gjrpc/pkg/jsonrpc"
	"strings"
)

type Router struct {
	handlers     Handlers
	convertError jsonrpc.ErrorConverter
}

func NewRouter(handlers Handlers, convertError jsonrpc.ErrorConverter) *Router {
	if convertError == nil {
		convertError = jsonrpc.DefaultErrorConverter
	}
	return &Router{
		convertError: convertError,
		handlers:     handlers,
	}
}

func (r *Router) notFound() (jsonrpc.Result, *jsonrpc.Error) {
	return nil, &jsonrpc.MethodNotFound
}

func (r *Router) Handle(req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	path := strings.Split(req.Method, ".")
	return r.handle(path, req)
}

func (r *Router) handle(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		return r.notFound()
	}
	switch path[0] {
	case "auth":
		return r.handleAuth(path[1:], req)
	case "catalog":
		return r.handleCatalog(path[1:], req)
	case "list":
		return r.handleList(path[1:], req)
	case "youtube":
		return r.handleYoutube(path[1:], req)
	}
	return r.notFound()
}

func (r *Router) handleAuth(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		return r.notFound()
	}
	switch path[0] {
	case "oauth":
		return r.handleAuthOauth(path[1:], req)
	case "status":
		return r.handleAuthStatus(path[1:], req)
	}
	return r.notFound()
}

func (r *Router) handleCatalog(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		return r.notFound()
	}
	switch path[0] {
	case "all":
		return r.handleCatalogAll(path[1:], req)
	}
	return r.notFound()
}

func (r *Router) handleList(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		return r.notFound()
	}
	switch path[0] {
	case "info":
		return r.handleListInfo(path[1:], req)
	case "items":
		return r.handleListItems(path[1:], req)
	case "sync":
		return r.handleListSync(path[1:], req)
	}
	return r.notFound()
}

func (r *Router) handleYoutube(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		return r.notFound()
	}
	switch path[0] {
	case "liked":
		return r.handleYoutubeLiked(path[1:], req)
	case "playlists":
		return r.handleYoutubePlaylists(path[1:], req)
	}
	return r.notFound()
}

func (r *Router) handleAuthOauth(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		res, err := r.handlers.Auth.Oauth(req.Context)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleAuthStatus(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		res, err := r.handlers.Auth.Status(req.Context)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleCatalogAll(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		res, err := r.handlers.Catalog.All(req.Context)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleListInfo(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		var request string
		if err := json.Unmarshal(req.Params, &request); err != nil {
			return r.convertError(err)
		}
		res, err := r.handlers.List.Info(req.Context, request)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleListItems(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		var request string
		if err := json.Unmarshal(req.Params, &request); err != nil {
			return r.convertError(err)
		}
		res, err := r.handlers.List.Items(req.Context, request)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleListSync(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		var request string
		if err := json.Unmarshal(req.Params, &request); err != nil {
			return r.convertError(err)
		}
		res, err := r.handlers.List.Sync(req.Context, request)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleYoutubeLiked(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		res, err := r.handlers.Youtube.Liked(req.Context)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}

func (r *Router) handleYoutubePlaylists(path []string, req *jsonrpc.Request) (jsonrpc.Result, *jsonrpc.Error) {
	if len(path) == 0 {
		res, err := r.handlers.Youtube.Playlists(req.Context)
		if err != nil {
			return r.convertError(err)
		}
		return res, nil
	}
	return r.notFound()
}
